//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis {
    public partial class AnnouncementsPage {
        protected global::System.Web.UI.WebControls.Repeater rptAnnouncements;
    }
}


