//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis {
    public partial class CompetitionPage {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlComp;
        protected global::System.Web.UI.WebControls.Literal litTitle;
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkRegister;
        protected global::System.Web.UI.WebControls.Image imgCover;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.Literal litMeta;
        protected global::System.Web.UI.WebControls.Repeater rptRegs;
        protected global::System.Web.UI.WebControls.Literal litNoRegs;
    }
}


