//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis
{


    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Repeater rptStories;
        protected global::System.Web.UI.WebControls.Repeater rptAnnouncements;
        protected global::System.Web.UI.WebControls.Repeater rptFeatures;
        protected global::System.Web.UI.WebControls.Repeater rptNews;
        protected global::System.Web.UI.WebControls.Repeater rptCoaches;
        protected global::System.Web.UI.WebControls.Repeater rptGallery;
        protected global::System.Web.UI.WebControls.Repeater rptFees;
        protected global::System.Web.UI.WebControls.Literal litContactAddress;
        protected global::System.Web.UI.WebControls.Literal litContactPhone;
        protected global::System.Web.UI.WebControls.Literal litContactEmail;
        protected global::System.Web.UI.WebControls.TextBox txtContactName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCN;
        protected global::System.Web.UI.WebControls.TextBox txtContactPhone;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCP;
        protected global::System.Web.UI.WebControls.DropDownList ddlContactSubject;
        protected global::System.Web.UI.WebControls.TextBox txtContactBody;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCB;
        protected global::System.Web.UI.WebControls.Button btnContactSubmit;
        protected global::System.Web.UI.WebControls.Literal litContactResult;
    }
}
