//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis {
    public partial class NewsPage {
        protected global::System.Web.UI.WebControls.Repeater rptNews;
    }
}


