//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis {
    public partial class ProductPage {
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
        protected global::System.Web.UI.WebControls.Panel pnlProduct;
        protected global::System.Web.UI.WebControls.Image imgMain;
        protected global::System.Web.UI.WebControls.Repeater rptThumbs;
        protected global::System.Web.UI.WebControls.Literal litName;
        protected global::System.Web.UI.WebControls.Literal litPrice;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.HiddenField hfProductId;
        protected global::System.Web.UI.WebControls.Button btnAdd;
    }
}


