//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis {
    
    public partial class Register {
        
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirst;
        
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLast;
        
        protected global::System.Web.UI.WebControls.Literal litCompTitle;
        
        protected global::System.Web.UI.WebControls.Literal litSingleFee;
        
        protected global::System.Web.UI.WebControls.Literal litDoubleFee;
        
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPhone;
        
        protected global::System.Web.UI.WebControls.TextBox txtBirthDate;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlGender;
        
        protected global::System.Web.UI.WebControls.TextBox txtNotes;
        
        protected global::System.Web.UI.WebControls.Button btnSubmit;
        
        protected global::System.Web.UI.WebControls.Literal litMsg;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnCompetitionId;
    }
}


