//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis {
    
    public partial class Store {
        
        protected global::System.Web.UI.WebControls.Repeater rptStoreBanners;

        protected global::System.Web.UI.WebControls.Repeater rptProducts;
    }
}


