//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis.Account {
    
    public partial class Panel {
        
        protected global::System.Web.UI.WebControls.Literal litUsername;
        
        protected global::System.Web.UI.WebControls.Literal litEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        
        protected global::System.Web.UI.WebControls.TextBox txtPhone;
        
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        
        protected global::System.Web.UI.WebControls.Literal litProfileMsg;
        
        protected global::System.Web.UI.WebControls.Repeater rptOrders;

        protected global::System.Web.UI.WebControls.Repeater rptMyRegs;

        protected global::System.Web.UI.WebControls.TextBox txtAddrTitle;
        protected global::System.Web.UI.WebControls.TextBox txtAddrReceiver;
        protected global::System.Web.UI.WebControls.TextBox txtAddrProvince;
        protected global::System.Web.UI.WebControls.TextBox txtAddrCity;
        protected global::System.Web.UI.WebControls.TextBox txtAddrAddress;
        protected global::System.Web.UI.WebControls.TextBox txtAddrPostal;
        protected global::System.Web.UI.WebControls.CheckBox chkAddrDefault;
        protected global::System.Web.UI.WebControls.HiddenField hdnAddrId;
        protected global::System.Web.UI.WebControls.Button btnSaveAddress;
        protected global::System.Web.UI.WebControls.Button btnCancelAddress;
        protected global::System.Web.UI.WebControls.Literal litAddrMsg;
        protected global::System.Web.UI.WebControls.Repeater rptAddresses;
    }
}


