//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pardis.Account {
    
    public partial class Register {
        
        protected global::System.Web.UI.WebControls.TextBox txtUser;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtPass;
        
        protected global::System.Web.UI.WebControls.Button btnRegister;
        
        protected global::System.Web.UI.WebControls.Literal litMsg;
    }
}


