//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PecPGW.Samples.WebApp.WebForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/NewIPGServices/bill/billservice.asmx")]
        public string PecPGW_Samples_WebApp_WebForms_ParsianPGWBillPaymentServices_BillService {
            get {
                return ((string)(this["PecPGW_Samples_WebApp_WebForms_ParsianPGWBillPaymentServices_BillService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/newipgservices/sale/saleservice.asmx")]
        public string PecPGW_Samples_WebApp_WebForms_ParsianPGWSalePaymentServices_SaleService {
            get {
                return ((string)(this["PecPGW_Samples_WebApp_WebForms_ParsianPGWSalePaymentServices_SaleService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/NewIPGServices/confirm/confirmservice.asmx")]
        public string PecPGW_Samples_WebApp_WebForms_ParsianPGWConfirmPaymentServices_ConfirmService {
            get {
                return ((string)(this["PecPGW_Samples_WebApp_WebForms_ParsianPGWConfirmPaymentServices_ConfirmService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("abcdef1ls")]
        public string LoginAccount {
            get {
                return ((string)(this["LoginAccount"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://pec.shaparak.ir/NewIPGServices/reverse/reversalservice.asmx")]
        public string PecPGW_Samples_WebApp_WebForms_ParsianPGWReversalServices_ReversalService {
            get {
                return ((string)(this["PecPGW_Samples_WebApp_WebForms_ParsianPGWReversalServices_ReversalService"]));
            }
        }
    }
}
