//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop1.Admin {
    
    public partial class CompetitionRegistrationsAdmin {
        
        protected global::System.Web.UI.WebControls.GridView gvRegs;
    }
}


