//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop1.Admin {
    
    public partial class CompetitionsAdmin {
        
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTitle;
        
        protected global::System.Web.UI.WebControls.TextBox txtLocation;
        
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        
        protected global::System.Web.UI.WebControls.TextBox txtDeadline;
        
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        
        protected global::System.Web.UI.WebControls.FileUpload fuCover;
        
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
        
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnId;
        
        protected global::System.Web.UI.WebControls.GridView gvCompetitions;
    }
}


