//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop1.Admin {
    
    public partial class GenericTableAdmin {
        
        /// <summary>
        /// litTableName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTableName;
        
        /// <summary>
        /// phMessages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phMessages;
        
        /// <summary>
        /// gvData control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvData;
        
        /// <summary>
        /// phInsert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phInsert;
        
        /// <summary>
        /// btnInsert control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnInsert;
    }
}


