//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace shop1.Admin {
    
    public partial class StoreAdmin {
        
        protected global::System.Web.UI.WebControls.TextBox txtName;
        
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvName;
        
        protected global::System.Web.UI.WebControls.TextBox txtPrice;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;

        protected global::System.Web.UI.WebControls.TextBox txtStock;
        
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        
        protected global::System.Web.UI.WebControls.FileUpload fuImage;
        
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.HiddenField hdnId;
        
        protected global::System.Web.UI.WebControls.GridView gvProducts;
    }
}


